optee.inc: update setting for OPTEE_ARCH
Issue: LIN1022-769

lib32-optee-os do_compile failed since OPTEE_ARCH is not set.
In file included from lib/libutee/include/link.h:9,
                 from lib/libutee/arch/arm/tcb.c:37:
lib/libutee/include/elf.h:67:2: error: #error Unknown architecture
   67 | #error Unknown architecture
      |  ^~~~~
In file included from lib/libutee/arch/arm/tcb.c:37:
lib/libutee/include/link.h:13:9: error: unknown type name 'Elf_Addr'
   13 |         Elf_Addr dlpi_addr;                     /* module relocation base */

(LOCAL REV: NOT UPSTREAM) -- send to meta-arm on 20220802

Signed-off-by: Changqing Li <changqing.li@windriver.com>